// Auth


export const GET_USER_INFO = ['GET_USER_INFO_LOADING', 'GET_USER_INFO_SUCCESS', 'GET_USER_INFO_FAIL'];
export const LOGIN = ['LOGIN_LOADING', 'LOGIN_SUCCESS', 'LOGIN_FAIL'];
export const HEALTH_CHECK = ['HEALTH_CHECK_LOADING', 'HEALTH_CHECK_SUCCESS', 'HEALTH_CHECK_FAIL'];
export const CHECK_DATABASE = ['CHECK_DATABASE_LOADING', 'CHECK_DATABASE_SUCCESS', 'CHECK_DATABASE_FAIL'];


export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';

export const GET_RESULT_LIST = ['GET_RESULT_LIST_LOADING', 'GET_RESULT_LIST_SUCCESS', 'GET_RESULT_LIST_FAIL'];

// Classroom
export const GET_CLASSROOM_LIST = ['GET_CLASSROOM_LIST_LOADING', 'GET_CLASSROOM_LIST_SUCCESS', 'GET_CLASSROOM_LIST_FAIL'];

// Course

export const GET_COURSE_VM_LIST = ['GET_COURSE_VM_LIST_LOADING', 'GET_COURSE_VM_LIST_SUCCESS', 'GET_COURSE_VM_LIST_FAIL'];
export const GET_COURSE_CON_LIST = ['GET_COURSE_CON_LIST_LOADING', 'GET_COURSE_CON_LIST_SUCCESS', 'GET_COURSE_CON_LIST_FAIL'];


export const GET_COURSE_LIST_ALL = ['GET_COURSE_LIST_ALL_LOADING', 'GET_COURSE_LIST_ALL_SUCCESS', 'GET_COURSE_LIST_ALL_FAIL'];
export const GET_COURSE_LIST_BY_LEVEL = ['GET_COURSE_LIST_BY_LEVEL_LOADING', 'GET_COURSE_LIST_BY_LEVEL_SUCCESS', 'GET_COURSE_LIST_BY_LEVEL_FAIL'];
export const GET_COURSE_DETAIL = ['GET_COURSE_DETAIL_LOADING', 'GET_COURSE_DETAIL_SUCCESS', 'GET_COURSE_DETAIL_FAIL'];

export const SEARCH_COURSE = ['SEARCH_COURSE_LOADING', 'SEARCH_COURSE_SUCCESS', 'SEARCH_COURSE_FAIL'];


// Job
export const LAUNCH_JOB = ['LAUNCH_JOB_LOADING', 'LAUNCH_JOB_SUCCESS', 'LAUNCH_JOB_FAIL'];


// User
export const GET_USER_COURSE_LIST = ['GET_USER_COURSE_LIST_LOADING', 'GET_USER_COURSE_LIST_SUCCESS', 'GET_USER_COURSE_LIST_FAIL'];
export const CREATE_USER_COURSE = ['CREATE_USER_COURSE_LOADING', 'CREATE_USER_COURSE_SUCCESS', 'CREATE_USER_COURSE_FAIL'];
export const UPDATE_USER_COURSE = ['UPDATE_USER_COURSE_LOADING', 'UPDATE_USER_COURSE_SUCCESS', 'UPDATE_USER_COURSE_FAIL'];
export const DELETE_USER_COURSE = ['DELETE_USER_COURSE_LOADING', 'DELETE_USER_COURSE_SUCCESS', 'DELETE_USER_COURSE_FAIL'];


// Proxy
export const RESET_AUTH = 'RESET_AUTH';

export const SIGNUP = ['SIGNUP_LOADING', 'SIGNUP_SUCCESS', 'SIGNUP_FAIL'];
export const LOGOUT = ['LOGOUT_LOADING', 'LOGOUT_SUCCESS', 'LOGOUT_FAIL'];

export const UPDATE_PROFILE = ['UPDATE_PROFILE_LOADING', 'UPDATE_PROFILE_SUCCESS', 'UPDATE_PROFILE_FAIL'];
export const GET_PROFILE = ['GET_PROFILE_LOADING', 'GET_PROFILE_SUCCESS', 'GET_PROFILE_FAIL'];
export const UPDATE_PASSWORD = ['UPDATE_PASSWORD_LOADING', 'UPDATE_PASSWORD_SUCCESS', 'UPDATE_PASSWORD_FAIL'];

export const GET_JOB_LIST = ['GET_JOB_LIST_LOADING', 'GET_JOB_LIST_SUCCESS', 'GET_JOB_LIST_FAIL'];
export const DELETE_JOB = ['DELETE_JOB_LOADING', 'DELETE_JOB_SUCCESS', 'DELETE_JOB_FAIL'];
export const GET_DATASETS_OPTS = ['GET_DATASETS_OPTS_LOADING', 'GET_DATASETS_OPTS_SUCCESS', 'GET_DATASETS_OPTS_FAIL'];
export const GET_IMAGES_OPTS = ['GET_IMAGES_OPTS_LOADING', 'GET_IMAGES_OPTS_SUCCESS', 'GET_IMAGES_OPTS_FAIL'];

// Sync
export const SET_USER_TOKEN = 'SET_USER_TOKEN';


export const RETRIEVE_TOKEN = ['RETRIEVE_TOKEN_LOADING', 'RETRIEVE_TOKEN_SUCCESS', 'RETRIEVE_TOKEN_FAIL'];

// Ui
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_DIALOG = 'OPEN_DIALOG';
