apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: demo-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  namespace: cht-demo
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: cht-demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      name: demo-pod
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: ogre0403/in-cluster:cht
        imagePullPolicy: Always