apiVersion: v1
kind: ServiceAccount
metadata:
  name: twgc-api-server
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: twgc-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  namespace: default
  name: twgc-api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twgc-api
spec:
  selector:
    matchLabels:
      tier: api-server
  replicas: 1
  template:
    metadata:
      name: api-server
      labels:
        tier: api-server
    spec:
      serviceAccountName: twgc-api-server
      containers:
      - name: twgc-api
        image: ogre0403/twgc:api-299f3bc-k8s
        ports:
        - containerPort: 38080
---
apiVersion: v1
kind: Service
metadata:
  name: twgc-api-svc
spec:
  ports:
    - port: 38080
  selector:
    tier: api-server