apiVersion: v1
kind: ServiceAccount
metadata:
  name: twgc-api-server
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: twgc-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  namespace: default
  name: twgc-api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twgc-api
spec:
  selector:
    matchLabels:
      tier: api-server
  replicas: 1
  template:
    metadata:
      name: api-server
      labels:
        tier: api-server
    spec:
      serviceAccountName: twgc-api-server
      containers:
      - name: twgc-api
        image: ogre0403/twgc:api-1c803ce
        ports:
        - containerPort: 38080
        volumeMounts:
        - name: twgc-api-conf
          mountPath: /etc/api-server/
      volumes:
      - name: twgc-api-conf
        configMap:
          name: twgc-api-cm
          items:
          - key: api-conf
            path: api-config.json
---
apiVersion: v1
kind: Service
metadata:
  name: twgc-api-svc
spec:
  ports:
    - port: 38080
  selector:
    tier: api-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: twgc-api-cm
data:
  api-conf: |-
    {
      "api-server": {
        "isOutsideCluster": false,
        "port": 38080,
        "provider": {
          "type": "go-oauth",
          "name": "test-provider",
          "client_id": "test_client_1",
          "client_secret": "test_secret",
          "auth_url": "http://140.110.5.22:30010/web/authorize",
          "token_url": "http://140.110.5.22:30010/v1/oauth/tokens",
          "refresh_url": "http://140.110.5.22:30010/v1/oauth/tokens",
          "introspect_url": "http://140.110.5.22:30010/v1/oauth/introspect",
          "logout_url": "http://140.110.5.22:30010/v1/oauth/logout",
          "redirect_url": "http://140.110.18.35:30004/user/course"
        }
      },
      "database": {
        "host": "twgc-database-svc.default",
        "port": 3306,
        "username": "twgc",
        "password": "twgc@NCHC",
        "database": "twgc"
      },
      "kubernetes": {
        "kubeconfig": "/etc/api-server/openstack-kubeconfig",
        "expose_ip": "http://140.110.5.22",
        "namespace": "default",
        "resourceLimit": {
          "cpu": "500m",
          "memory": "64Mi"
        },
        "expose_port": {
          "web": 80,
          "jupyter": 8888,
          "digitis": 5000,
          "ttyd": 7681
        }
      }
    }