apiVersion: apps/v1
kind: Deployment
metadata:
  name: twgc-ui
spec:
  selector:
    matchLabels:
      tier: twgc-ui
  replicas: 1
  template:
    metadata:
      name: twgc-ui
      labels:
        tier: twgc-ui
    spec:
      containers:
      - name: twgc-ui
        image: ogre0403/twgc:ui-c82ee76
        ports:
        - containerPort: 30014
        volumeMounts:
        - name: twgc-ui-conf
          mountPath: /go/src/gitlab.com/nchc-ai/AI-Eduational-Platform/frontend/app/config/
      volumes:
      - name: twgc-ui-conf
        configMap:
          name: twgc-ui-cm
          items:
          - key: endpoint-conf
            path: api.js
---
apiVersion: v1
kind: Service
metadata:
  name: twgc-ui
spec:
  type: NodePort
  ports:
    - port: 30014
      nodePort: 30014
  selector:
    tier: twgc-ui
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: twgc-ui-cm
data:
  endpoint-conf: |-
    export const WEBSITE_URL = 'http://140.110.136.74:30014';
    export const API_URL = '';
    export const AUTH_PROVIDER_URL = 'http://140.110.5.22:30010';
