apiVersion: apps/v1
kind: Deployment
metadata:
  name: twgc-database
spec:
  selector:
    matchLabels:
      tier: mysql
  replicas: 1
  template:
    metadata:
      name: mysql-pod
      labels:
        tier: mysql
    spec:
      containers:
      - name: twgc-database
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ogre0403
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: twgc-database-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: twgc-database-init
        configMap:
          name: twgc-database-cm
          items:
          - key: database-init
            path: init.sql
---
apiVersion: v1
kind: Service
metadata:
  name: twgc-database-svc
spec:
  ports:
    - port: 3306
  selector:
    tier: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: twgc-database-cm
data:
  database-init: |-
    CREATE DATABASE twgc;
    CREATE USER 'twgc'@'localhost' IDENTIFIED BY 'twgc@NCHC';
    CREATE USER 'twgc'@'%' IDENTIFIED BY 'twgc@NCHC';
    GRANT ALL ON twgc.* TO 'twgc'@'localhost';
    GRANT ALL ON twgc.* TO 'twgc'@'%';
