// Auth

export const LOGIN = ['LOGIN_LOADING', 'LOGIN_SUCCESS', 'LOGIN_FAIL'];
export const HEALTH_CHECK = ['HEALTH_CHECK_LOADING', 'HEALTH_CHECK_SUCCESS', 'HEALTH_CHECK_FAIL'];
export const CHECK_DATABASE = ['CHECK_DATABASE_LOADING', 'CHECK_DATABASE_SUCCESS', 'CHECK_DATABASE_FAIL'];


export const SET_USER_INFO = 'SET_USER_INFO';


export const GET_RESULT_LIST = ['GET_RESULT_LIST_LOADING', 'GET_RESULT_LIST_SUCCESS', 'GET_RESULT_LIST_FAIL'];


// User
export const GET_USER_COURSE_LIST = ['GET_USER_COURSE_LIST_LOADING', 'GET_USER_COURSE_LIST_SUCCESS', 'GET_USER_COURSE_LIST_FAIL'];
export const CREATE_USER_COURSE = ['CREATE_USER_COURSE_LOADING', 'CREATE_USER_COURSE_SUCCESS', 'CREATE_USER_COURSE_FAIL'];
