	<header id="js-header" class="u-header u-header--static">
		<div class="u-header__section u-header__section--light g-bg-white g-transition-0_3 g-py-10">
			<nav class="js-mega-menu navbar navbar-expand-lg hs-menu-initialized hs-menu-horizontal">
				<div class="container">
					<button class="navbar-toggler navbar-toggler-right btn g-line-height-1 g-brd-none g-pa-0 g-pos-abs g-top-3 g-right-0" type="button" aria-label="Toggle navigation" aria-expanded="false" aria-controls="navBar" data-toggle="collapse" data-target="#navBar">
						<span class="hamburger hamburger--slider">
						<span class="hamburger-box">
						<span class="hamburger-inner">
						</span>
						</span>
						</span>
					</button>
					<a href="index.aspx" class="navbar-brand"><img src="img/TWGC_logo.jpg" alt="Image Description"></a>
					<div class="collapse navbar-collapse align-items-center flex-sm-row g-pt-10 g-pt-5--lg g-mr-40--lg" id="navBar">
						<ul class="navbar-nav text-uppercase g-pos-rel g-font-weight-600 ml-auto" style="font-size:16px;">
							<li class="nav-item g-mx-10--lg g-mx-15--xl active"><a href="index.aspx" class="nav-link g-py-17 g-px-0"> <i class="ace-icon fa fa-home"></i> 首頁</a></li>
							<li class="nav-item g-mx-10--lg g-mx-15--xl"><a href="https://github.com/TW-NCHC/TWGC" target="_blank" class="nav-link g-py-17 g-px-0"> <i class="ace-icon fa fa-github"></i> NCHC Github</a></li>
							<li class="nav-item hs-has-sub-menu  g-mx-10--lg g-mx-15--xl" data-animation-in="fadeIn" data-animation-out="fadeOut">
								<a id="nav-link--features" class="nav-link g-py-17 g-px-0" href="#!" aria-haspopup="true" aria-expanded="false" aria-controls="nav-submenu--features"> <i class="ace-icon fa fa-bullhorn"></i> 最新消息</a>
								<ul class="hs-sub-menu list-unstyled u-shadow-v11 g-brd-top g-brd-primary g-brd-top-2 g-min-width-220 g-mt-18 g-mt-8--lg--scrolling" id="nav-submenu--features" aria-labelledby="nav-link--features">
									<li class="dropdown-item "><a class="nav-link" href="announce_01.aspx">一般公告</a></li>
									<li class="dropdown-item "><a class="nav-link" href="announce_02.aspx">教育訓練</a></li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
	</header>